### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Padraogh** [pubgsh/api#5]
apazzolini-
No issue, just a feature request. If you could add a way to "Create a Gif" from a selected part of the replay, this would be very useful in sharing info with other teammates, especially on mobile. Good job on the app, keep it up!

**Comment by apazzolini** [comment]
Hey, I agree that this is a cool feature, and I actually already have a note tracking it on the roadmap. It's tough to implement, so I probably won't get to it for a while.

In the meantime, you can check out https://www.getcloudapp.com/ (though it's not mobile friendly AFAIK).

I'm going to close this issue since it's related to the client, not the api, and I already have a note.

Thanks for the kind words!
